[package]
name = "lt-fm-index"
version = "0.3.1"
authors = ["baku4 <bahkhun@gmail.com>"]
edition = "2018"
description = "Fm-index using k-mer lookup table for exact pattern matching"
readme = "README.md"
repository = "https://github.com/baku4/lt-fm-index/"
license = "MIT"
keywords = ["fm-index", "bwt", "pattern_matching", "bio"]
categories = ["science", "algorithms"]

[dependencies]
anyhow = "1.0.44"
libdivsufsort-rs = "0.1.1"
serde = "1.0.127"
bincode = "1.3.3"

[dev-dependencies]
crate_fm_index = { package = "fm-index", version = "0.1" }
rand = "0.8.0"
criterion = "0.3.5"

[[bench]]
name = "benchmark"
harness = false