[package]
name = "lt-fm-index"
version = "0.1.0"
authors = ["baku4 <bahkhun@gmail.com>"]
edition = "2018"
description = "Fm-index using k-mer lookup table for exact pattern matching"
readme = "README.md"
repository = "https://github.com/baku4/lt-fm-index/"
license = "MIT"
keywords = ["fm-index", "bwt", "pattern_matching", "bio"]
categories = ["science", "algorithms"]

[dependencies]
libdivsufsort-rs = "0.1.0"

[dev-dependencies]
fm-index = "0.1"
criterion = "0.3.4"

[[bench]]
name = "benchmark"
harness = false