name: CI

on:
  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --verbose
      - name: Upload target dir
        uses: actions/upload-artifact@v4
        with:
          name: target-${{ matrix.os }}
          path: target

  test:
    needs: build
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Restore target dir
        uses: actions/download-artifact@v4
        with:
          name: target-${{ matrix.os }}
          path: target
      - name: Run tests without features
        run: cargo test --verbose
      - name: Run tests with fastbwt feature
        run: cargo test --features fastbwt --verbose
      - name: Run tests with async-io feature
        run: cargo test --features async-io --verbose

  wasm-build:
    name: Build as WASM
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@stable      
      - name: Cache cargo dependencies
        uses: Swatinem/rust-cache@v2
      - name: Add build target
        run: rustup target add wasm32-unknown-unknown
      - name: Build
        run: cargo build --target wasm32-unknown-unknown --verbose